"""Database Creation

Revision ID: 4b91b7ae280a
Revises: 3a568b3ef9d5
Create Date: 2023-06-23 01:20:47.955026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b91b7ae280a'
down_revision = '3a568b3ef9d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('plate', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('plate')
    )
    op.add_column('users', sa.Column('trip_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'trip_count')
    op.drop_table('cars')
    # ### end Alembic commands ###
